### ISSUE TITLE
[항공편 예약 team1] 남은 할일 정리

### ISSUE THREAD

**Issue by HJ-Woo** [Spring-Study-20210220/Airplane_Reservation#1]
![image](https://user-images.githubusercontent.com/59992230/113010025-78fdbb00-91b3-11eb-9545-7d44003b0b00.png)

- [x]  위 ERD에서 ``Airplane``의 역할에 대해 고민하기
   - 1. capacity만 보유하는 OneToOne 관계라면, Schedule에 합치기
   - 2. *항공편*의 의미를 가지려면 ``Schedule``로부터 ``Time`` 구분 두가지 가져오기

- [x]  ``AirlineGrade``를 어떻게 결정할지 고민하기
   - 1. 항공사별 다른 등급의 역할로 저장해둘것인지?
   - 2. entity를 제거하고 ``User``에 동일 등급으로 포함시킬 것인지?

- [x]  결제 구현 여부에 대해 논의하기

**Comment by timel2ss** [comment]
Airplane을 처음 구상한 의도
- 기내의 좌석이 총 몇 석 존재하는지 정보를 표현하기 위해
- 각 좌석에 대한 예약 여부 조회 등등

Airplane이 없다면?
- Schedule에 airplane의 이름? 기명? + 수용 가능 인원에 대한 필드 추가
- 하지만 같은 airplane에 대한 여러 스케줄에 경우 DB에 중복되는 데이터가 발생 (정규화??)

Schedule이 직접 Seat과 의존관계를 맺고 + 추가적으로 Airplane을 embeddable로 정의하는 것은 어떨까?
https://velog.io/@conatuseus/JPA-%EC%9E%84%EB%B2%A0%EB%94%94%EB%93%9C-%ED%83%80%EC%9E%85embedded-type-8ak3ygq8wo

AirlineGrade
유저 등급은 가격 할인과 관련되는 부분이 크다고 생각한다.
항공사마다 가격 책정을 다르게 할 것이라고 생각하여 위와 같이 설계하자고 제안했다.
하지만 정작 존재하지도 않을 가상의 항공사를 만들고 있는데, 각 항공사의 가격 정책을 별개로 정하는 것은 너무 깊게 생각했던 것 같기도 하다.
따라서 항공사 전체와 통합된 애플리케이션이라고 가정하고 User에 동일 등급으로 하는 편이 더 나은 선택으로 보인다.

결제 구현 여부
만약 결제를 구현한다고 하면 가격 책정을 결정하는 것이 중요해 보인다.
가격에 영향을 주는 것은 좌석 클래스와 비행 시간, 유저 등급 정도가 될 것으로 보인다.
유저 등급을 모든 항공사에 통합시키고 진행한다면 크게 복잡하지는 않을 것 같다.

클래스별 가격차이는 평균적으로 이코노미 : 비즈니스 : 퍼스트 = 1 : 4 : 8 정도라고 나온다.
정확한 수치인지는 모르겠다. 우리가 임의로 결정하면 될 부분이라고 생각된다.

비행 시간은 시간 비례로 값을 증가시키고, 유저 등급도 등급별로 고정 금액 할인 or 퍼센트 할인 등의 정책을 결정하면 될 것 같다.
